import { useEffect, useState } from 'react';
import AdminExportActions from '../../components/common/AdminExportActions';
import { apiRequest } from '../../config/api';

const emptyForm={code:'',description:'',discountPercentage:'',maximumDiscountAmount:'',minimumOrderAmount:'',usageLimit:'',startDate:new Date().toISOString().slice(0,10),endDate:'',isActive:true};
const normalize=c=>({...c, startDate:(c.startDate||'').slice(0,10),endDate:(c.endDate||'').slice(0,10)});
export default function CouponManage(){
 const [coupons,setCoupons]=useState([]),[form,setForm]=useState(emptyForm),[editingId,setEditingId]=useState(null),[viewing,setViewing]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);setError('');try{setCoupons((await apiRequest('/Coupon')).map(normalize))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();if(!form.code.trim()){setError('Coupon code is required.');return}const payload={code:form.code.trim().toUpperCase(),description:form.description,discountPercentage:Number(form.discountPercentage||0),maximumDiscountAmount:form.maximumDiscountAmount?Number(form.maximumDiscountAmount):null,minimumOrderAmount:form.minimumOrderAmount?Number(form.minimumOrderAmount):null,usageLimit:Number(form.usageLimit||0),startDate:form.startDate,endDate:form.endDate||form.startDate,isActive:form.isActive};setError('');try{if(editingId)await apiRequest(`/Coupon/${editingId}`,{method:'PUT',body:JSON.stringify(payload)});else await apiRequest('/Coupon',{method:'POST',body:JSON.stringify(payload)});setForm(emptyForm);setEditingId(null);await load()}catch(e){setError(e.message)}};
 const edit=c=>{setEditingId(c.id);setForm({code:c.code,description:c.description||'',discountPercentage:c.discountPercentage,maximumDiscountAmount:c.maximumDiscountAmount??'',minimumOrderAmount:c.minimumOrderAmount??'',usageLimit:c.usageLimit??'',startDate:c.startDate,endDate:c.endDate,isActive:c.isActive})};
 const remove=async id=>{if(!window.confirm('Delete this coupon?'))return;try{await apiRequest(`/Coupon/${id}`,{method:'DELETE'});await load()}catch(e){setError(e.message)}};
 const toggle=async id=>{try{await apiRequest(`/Coupon/${id}/toggle`,{method:'PATCH'});await load()}catch(e){setError(e.message)}};
 return <div><header style={headerStyle}><div><h1 style={titleStyle}>Coupon Management</h1><p style={mutedStyle}>Create, edit, activate, and delete real coupons.</p></div><AdminExportActions filename="coupons" title="Coupon Report" rows={coupons.map(c=>({ID:c.id,Code:c.code,Discount:`${c.discountPercentage}%`,Usage:c.usageLimit,Used:c.usedCount,Status:c.isActive?'Active':'Inactive'}))}/></header>
 {error&&<div style={errorStyle}>{error}</div>}
 <form onSubmit={save} style={formStyle}><input placeholder="Coupon code" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} style={inputStyle}/><input placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} style={inputStyle}/><input type="number" min="0" max="100" step="0.01" placeholder="Discount %" value={form.discountPercentage} onChange={e=>setForm({...form,discountPercentage:e.target.value})} style={inputStyle}/><input type="number" min="0" placeholder="Minimum order" value={form.minimumOrderAmount} onChange={e=>setForm({...form,minimumOrderAmount:e.target.value})} style={inputStyle}/><input type="number" min="0" placeholder="Usage limit (0 = unlimited)" value={form.usageLimit} onChange={e=>setForm({...form,usageLimit:e.target.value})} style={inputStyle}/><input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})} style={inputStyle}/><input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})} style={inputStyle}/><label style={checkStyle}><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label><button style={buttonStyle}>{editingId?'Update Coupon':'Add Coupon'}</button>{editingId&&<button type="button" onClick={()=>{setEditingId(null);setForm(emptyForm)}} style={secondaryButton}>Cancel</button>}</form>
 <section style={panelStyle}><div style={{overflowX:'auto'}}><table style={tableStyle}><thead><tr><th style={thStyle}>ID</th><th style={thStyle}>Code</th><th style={thStyle}>Discount</th><th style={thStyle}>Usage</th><th style={thStyle}>Status</th><th style={thStyle}>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="6" style={tdStyle}>Loading...</td></tr>:coupons.map(c=><tr key={c.id}><td style={tdStyle}>{c.id}</td><td style={tdStyle}>{c.code}</td><td style={tdStyle}>{c.discountPercentage}%</td><td style={tdStyle}>{c.usedCount}/{c.usageLimit||'∞'}</td><td style={tdStyle}><button onClick={()=>toggle(c.id)} style={miniButton}>{c.isActive?'Active':'Inactive'}</button></td><td style={tdStyle}><button onClick={()=>setViewing(c)} style={miniButton}>View</button>{' '}<button onClick={()=>edit(c)} style={miniButton}>Edit</button>{' '}<button onClick={()=>remove(c.id)} style={{...miniButton,background:'#fee2e2',color:'#991b1b'}}>Delete</button></td></tr>)}</tbody></table></div></section>
 {viewing&&<div style={modalBackdrop}><div style={modalStyle}><h2>{viewing.code}</h2><p>{viewing.description||'No description.'}</p><p>Discount: {viewing.discountPercentage}%</p><p>Valid: {viewing.startDate} to {viewing.endDate}</p><button onClick={()=>setViewing(null)} style={buttonStyle}>Close</button></div></div>}</div>
}
const titleStyle={fontSize:28,fontWeight:800,color:'#62b7f5',margin:0},mutedStyle={color:'#9fb6cc',fontSize:14},headerStyle={display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap',marginBottom:18},panelStyle={background:'#0d1b2e',borderRadius:18,padding:18},formStyle={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10,background:'#0d1b2e',borderRadius:12,padding:16,marginBottom:18},inputStyle={width:'100%',boxSizing:'border-box',padding:10,border:'1px solid #345',borderRadius:8,background:'#132840',color:'#e5eef8'},checkStyle={display:'flex',alignItems:'center',gap:8,color:'#e5eef8'},buttonStyle={border:'none',background:'linear-gradient(90deg,#0f4c81,#14919b)',color:'#fff',borderRadius:8,padding:'10px 16px',fontWeight:700,cursor:'pointer'},secondaryButton={...buttonStyle,background:'#334155'},miniButton={border:'1px solid #345',background:'#132840',color:'#e5eef8',borderRadius:8,padding:'6px 10px',fontSize:12,cursor:'pointer'},tableStyle={width:'100%',borderCollapse:'collapse'},thStyle={padding:'12px 10px',textAlign:'left',color:'#9fb6cc'},tdStyle={padding:'12px 10px',color:'#e5eef8',borderBottom:'1px solid #203852'},errorStyle={background:'#fef3f2',color:'#b42318',padding:12,borderRadius:8,marginBottom:18},modalBackdrop={position:'fixed',inset:0,background:'rgba(0,0,0,.5)',display:'grid',placeItems:'center',zIndex:20},modalStyle={background:'#0d1b2e',color:'#e5eef8',borderRadius:12,padding:24,minWidth:300};
