import { useEffect, useState } from 'react';
import AdminExportActions from '../../components/common/AdminExportActions';
import { apiRequest } from '../../config/api';

const emptyForm={userId:'',storeName:'',storeDescription:'',phone:'',address:''};
export default function VendorManage(){
 const [vendors,setVendors]=useState([]),[users,setUsers]=useState([]),[form,setForm]=useState(emptyForm),[editingId,setEditingId]=useState(null),[viewing,setViewing]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [vs,us]=await Promise.all([apiRequest('/Vendor'),apiRequest('/Admin/users')]);setVendors(vs);setUsers(us.filter(u=>u.role==='Customer'||u.role==='Vendor'))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const availableUsers=users.filter(u=>!vendors.some(v=>v.userId===u.id)||u.id===Number(form.userId));
 const save=async e=>{e.preventDefault();if(!form.userId||!form.storeName.trim()){setError('Select a user and enter a store name.');return}setSaving(true);setError('');try{const payload={...form,userId:Number(form.userId)};if(editingId)await apiRequest(`/Vendor/${editingId}`,{method:'PUT',body:JSON.stringify({id:editingId,...payload})});else await apiRequest('/Vendor',{method:'POST',body:JSON.stringify(payload)});setForm(emptyForm);setEditingId(null);await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const edit=v=>{setEditingId(v.id);setForm({userId:v.userId,storeName:v.storeName,storeDescription:v.storeDescription||'',phone:v.phone||'',address:v.address||''})};
 const remove=async id=>{if(!window.confirm('Delete this vendor profile?'))return;try{await apiRequest(`/Vendor/${id}`,{method:'DELETE'});await load()}catch(e){setError(e.message)}};
 const decision=async(id,action)=>{try{await apiRequest(`/Vendor/${id}/${action}`,{method:'PATCH'});await load()}catch(e){setError(e.message)}};
 const [rateDraft,setRateDraft]=useState({});
 const saveCommissionRate=async id=>{const raw=rateDraft[id];const value=raw===''||raw===undefined?null:Number(raw);if(value!==null&&(isNaN(value)||value<0||value>100)){setError('Commission rate must be between 0 and 100.');return}try{await apiRequest(`/Vendor/${id}/commission-rate`,{method:'PATCH',body:JSON.stringify({commissionRateOverride:value})});setRateDraft(d=>{const n={...d};delete n[id];return n});await load()}catch(e){setError(e.message)}};
 return <div><header style={headerStyle}><div><h1 style={titleStyle}>Vendor Management</h1><p style={mutedStyle}>Onboard users, manage vendor profiles, approve stores, and set commission rates.</p></div><AdminExportActions filename="vendors" title="Vendor Report" rows={vendors.map(v=>({ID:v.id,Vendor:v.storeName,Owner:v.ownerName,Email:v.ownerEmail,Products:v.productCount,Status:v.isApproved?'Approved':'Pending',CommissionOverride:v.commissionRateOverride!=null?`${v.commissionRateOverride}%`:'Category rate',PayableBalance:v.payableBalance}))}/></header>
 {error&&<div style={errorStyle}>{error}</div>}
 <form onSubmit={save} style={formStyle}><select value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})} style={inputStyle}><option value="">Select user for vendor onboarding</option>{availableUsers.map(u=><option key={u.id} value={u.id}>{u.fullName} — {u.email}</option>)}</select><input placeholder="Store name" value={form.storeName} onChange={e=>setForm({...form,storeName:e.target.value})} style={inputStyle}/><input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} style={inputStyle}/><input placeholder="Address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} style={inputStyle}/><input placeholder="Store description" value={form.storeDescription} onChange={e=>setForm({...form,storeDescription:e.target.value})} style={inputStyle}/><button disabled={saving} style={buttonStyle}>{saving?'Saving...':editingId?'Update Vendor':'Add Vendor'}</button>{editingId&&<button type="button" onClick={()=>{setEditingId(null);setForm(emptyForm)}} style={secondaryButton}>Cancel</button>}</form>
 <section style={panelStyle}><div style={{overflowX:'auto'}}><table style={tableStyle}><thead><tr><th style={thStyle}>ID</th><th style={thStyle}>Store</th><th style={thStyle}>Owner</th><th style={thStyle}>Products</th><th style={thStyle}>Status</th><th style={thStyle}>Commission %</th><th style={thStyle}>Payable</th><th style={thStyle}>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="8" style={tdStyle}>Loading...</td></tr>:vendors.map(v=><tr key={v.id}><td style={tdStyle}>{v.id}</td><td style={tdStyle}>{v.storeName}</td><td style={tdStyle}>{v.ownerName}</td><td style={tdStyle}>{v.productCount}</td><td style={tdStyle}>{v.isApproved?'Approved':'Pending'}</td><td style={tdStyle}><input type="number" min="0" max="100" step="0.1" placeholder={v.commissionRateOverride!=null?String(v.commissionRateOverride):'Category rate'} value={rateDraft[v.id]??''} onChange={e=>setRateDraft(d=>({...d,[v.id]:e.target.value}))} style={{...inputStyle,width:90,padding:6}}/>{' '}<button onClick={()=>saveCommissionRate(v.id)} style={miniButton}>Set</button></td><td style={tdStyle}>৳{Number(v.payableBalance||0).toFixed(2)}</td><td style={tdStyle}><button onClick={()=>setViewing(v)} style={miniButton}>View</button>{' '}<button onClick={()=>edit(v)} style={miniButton}>Edit</button>{' '}<button onClick={()=>decision(v.id,v.isApproved?'reject':'approve')} style={miniButton}>{v.isApproved?'Reject':'Approve'}</button>{' '}<button onClick={()=>remove(v.id)} style={{...miniButton,background:'#fee2e2',color:'#991b1b'}}>Delete</button></td></tr>)}</tbody></table></div></section>
 {viewing&&<div style={modalBackdrop}><div style={modalStyle}><h2>{viewing.storeName}</h2><p>Owner: {viewing.ownerName}</p><p>Email: {viewing.ownerEmail}</p><p>Phone: {viewing.phone||'-'}</p><p>Address: {viewing.address||'-'}</p><p>Status: {viewing.isApproved?'Approved':'Pending'}</p><p>Commission Override: {viewing.commissionRateOverride!=null?`${viewing.commissionRateOverride}%`:'Uses category rate'}</p><p>Payable Balance: ৳{Number(viewing.payableBalance||0).toFixed(2)}</p><button onClick={()=>setViewing(null)} style={buttonStyle}>Close</button></div></div>}</div>
}
const titleStyle={fontSize:28,fontWeight:800,color:'#62b7f5',margin:0},mutedStyle={color:'#9fb6cc',fontSize:14},headerStyle={display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap',marginBottom:18},panelStyle={background:'#0d1b2e',borderRadius:18,padding:18},formStyle={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,background:'#0d1b2e',borderRadius:12,padding:16,marginBottom:18},inputStyle={width:'100%',boxSizing:'border-box',padding:10,border:'1px solid #345',borderRadius:8,background:'#132840',color:'#e5eef8'},buttonStyle={border:'none',background:'linear-gradient(90deg,#0f4c81,#14919b)',color:'#fff',borderRadius:8,padding:'10px 16px',fontWeight:700,cursor:'pointer'},secondaryButton={...buttonStyle,background:'#334155'},miniButton={border:'1px solid #345',background:'#132840',color:'#e5eef8',borderRadius:8,padding:'6px 10px',fontSize:12,cursor:'pointer'},tableStyle={width:'100%',borderCollapse:'collapse'},thStyle={padding:'12px 10px',textAlign:'left',color:'#9fb6cc'},tdStyle={padding:'12px 10px',color:'#e5eef8',borderBottom:'1px solid #203852',whiteSpace:'nowrap'},errorStyle={background:'#fef3f2',color:'#b42318',padding:12,borderRadius:8,marginBottom:18},modalBackdrop={position:'fixed',inset:0,background:'rgba(0,0,0,.5)',display:'grid',placeItems:'center',zIndex:20},modalStyle={background:'#0d1b2e',color:'#e5eef8',borderRadius:12,padding:24,minWidth:320};
