import { useEffect, useMemo, useState } from 'react';
import AdminExportActions from '../../components/common/AdminExportActions';
import { apiRequest } from '../../config/api';

const emptyForm={name:'',description:'',imageUrl:'',isActive:true};
export default function CategoryManage(){
 const [categories,setCategories]=useState([]),[form,setForm]=useState(emptyForm),[editingId,setEditingId]=useState(null),[viewing,setViewing]=useState(null),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);setError('');try{setCategories(await apiRequest('/Category'));}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>categories.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())),[categories,search]);
 const save=async e=>{e.preventDefault();if(!form.name.trim()){setError('Category name is required.');return}setError('');try{const payload={...form,name:form.name.trim()};if(editingId)await apiRequest(`/Category/${editingId}`,{method:'PUT',body:JSON.stringify({id:editingId,...payload})});else await apiRequest('/Category',{method:'POST',body:JSON.stringify(payload)});setForm(emptyForm);setEditingId(null);await load()}catch(e){setError(e.message)}};
 const edit=c=>{setEditingId(c.id);setForm({name:c.name,description:c.description||'',imageUrl:c.imageUrl||'',isActive:c.isActive})};
 const remove=async id=>{if(!window.confirm('Delete this category?'))return;try{await apiRequest(`/Category/${id}`,{method:'DELETE'});await load()}catch(e){setError(e.message)}};
 const toggle=async c=>{try{await apiRequest(`/Category/${c.id}/toggle`,{method:'PATCH'});await load()}catch(e){setError(e.message)}};
 return <div><header style={headerStyle}><div><h1 style={titleStyle}>Category Management</h1><p style={mutedStyle}>Create and manage categories using the database.</p></div><AdminExportActions filename="categories" title="Category Report" rows={categories.map(c=>({ID:c.id,Name:c.name,Products:c.productCount,Status:c.isActive?'Active':'Inactive'}))}/></header>
 {error&&<div style={errorStyle}>{error}</div>}
 <form onSubmit={save} style={formStyle}><input placeholder="Category name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} style={inputStyle}/><input placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} style={inputStyle}/><input placeholder="Image URL (optional)" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} style={inputStyle}/><label style={checkStyle}><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label><button style={buttonStyle}>{editingId?'Update Category':'Add Category'}</button>{editingId&&<button type="button" onClick={()=>{setEditingId(null);setForm(emptyForm)}} style={secondaryButton}>Cancel</button>}</form>
 <section style={panelStyle}><input placeholder="Search categories..." value={search} onChange={e=>setSearch(e.target.value)} style={{...inputStyle,maxWidth:340,marginBottom:14}}/><div style={{overflowX:'auto'}}><table style={tableStyle}><thead><tr><th style={thStyle}>ID</th><th style={thStyle}>Name</th><th style={thStyle}>Products</th><th style={thStyle}>Status</th><th style={thStyle}>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="5" style={tdStyle}>Loading...</td></tr>:filtered.map(c=><tr key={c.id}><td style={tdStyle}>{c.id}</td><td style={tdStyle}>{c.name}</td><td style={tdStyle}>{c.productCount??0}</td><td style={tdStyle}><button onClick={()=>toggle(c)} style={miniButton}>{c.isActive?'Active':'Inactive'}</button></td><td style={tdStyle}><button onClick={()=>setViewing(c)} style={miniButton}>View</button>{' '}<button onClick={()=>edit(c)} style={miniButton}>Edit</button>{' '}<button onClick={()=>remove(c.id)} style={{...miniButton,background:'#fee2e2',color:'#991b1b'}}>Delete</button></td></tr>)}</tbody></table></div></section>
 {viewing&&<div style={modalBackdrop}><div style={modalStyle}><h2>{viewing.name}</h2><p>{viewing.description||'No description.'}</p><p>Products: {viewing.productCount??0}</p><p>Status: {viewing.isActive?'Active':'Inactive'}</p><button onClick={()=>setViewing(null)} style={buttonStyle}>Close</button></div></div>}</div>
}
const titleStyle={fontSize:28,fontWeight:800,color:'#62b7f5',margin:0},mutedStyle={color:'#9fb6cc',fontSize:14},headerStyle={display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap',marginBottom:18},panelStyle={background:'#0d1b2e',borderRadius:18,padding:18},formStyle={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10,background:'#0d1b2e',borderRadius:12,padding:16,marginBottom:18},inputStyle={width:'100%',boxSizing:'border-box',padding:10,border:'1px solid #345',borderRadius:8,background:'#132840',color:'#e5eef8'},checkStyle={display:'flex',alignItems:'center',gap:8,color:'#e5eef8'},buttonStyle={border:'none',background:'linear-gradient(90deg,#0f4c81,#14919b)',color:'#fff',borderRadius:8,padding:'10px 16px',fontWeight:700,cursor:'pointer'},secondaryButton={...buttonStyle,background:'#334155'},miniButton={border:'1px solid #345',background:'#132840',color:'#e5eef8',borderRadius:8,padding:'6px 10px',fontSize:12,cursor:'pointer'},tableStyle={width:'100%',borderCollapse:'collapse'},thStyle={padding:'12px 10px',textAlign:'left',color:'#9fb6cc'},tdStyle={padding:'12px 10px',color:'#e5eef8',borderBottom:'1px solid #203852'},errorStyle={background:'#fef3f2',color:'#b42318',padding:12,borderRadius:8,marginBottom:18},modalBackdrop={position:'fixed',inset:0,background:'rgba(0,0,0,.5)',display:'grid',placeItems:'center',zIndex:20},modalStyle={background:'#0d1b2e',color:'#e5eef8',borderRadius:12,padding:24,minWidth:300};
